{"uuid":"5721cb0d-7de9-4975-873f-22df679c3990","historyId":"c36d7339bf4ae655289298a4091dce63","fullName":"tests.LoginTests.invalidLoginTest_InvalidUserNameInvalidPassword","labels":[{"name":"package","value":"tests.LoginTests"},{"name":"testClass","value":"tests.LoginTests"},{"name":"testMethod","value":"invalidLoginTest_InvalidUserNameInvalidPassword"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"Exo3"},{"name":"subSuite","value":"tests.LoginTests"},{"name":"host","value":"DESKTOP-A2LBKSC"},{"name":"thread","value":"21052@DESKTOP-A2LBKSC.main(1)"},{"name":"epic","value":"Regression Tests"},{"name":"feature","value":"Login Tests"},{"name":"story","value":"Invalid username and password login test"},{"name":"severity","value":"blocker"}],"links":[],"name":"Invalid Login Scenario with wrong username and password.","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Cannot run program \"C:\\Program\": CreateProcess error=2, The system cannot find the file specified","trace":"java.io.IOException: Cannot run program \"C:\\Program\": CreateProcess error=2, The system cannot find the file specified\r\n\tat java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)\r\n\tat java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)\r\n\tat java.base/java.lang.Runtime.exec(Runtime.java:635)\r\n\tat java.base/java.lang.Runtime.exec(Runtime.java:459)\r\n\tat java.base/java.lang.Runtime.exec(Runtime.java:356)\r\n\tat pages.OpenUrl.goToN11(OpenUrl.java:40)\r\n\tat tests.LoginTests.invalidLoginTest_InvalidUserNameInvalidPassword(LoginTests.java:40)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:564)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)\r\n\tat org.testng.internal.Invoker.invokeMethod(Invoker.java:580)\r\n\tat org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)\r\n\tat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:648)\r\n\tat org.testng.TestRunner.run(TestRunner.java:505)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:455)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:364)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1137)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1049)\r\n\tat org.testng.TestNG.run(TestNG.java:1017)\r\n\tat org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)\r\n\tat org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)\r\nCaused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified\r\n\tat java.base/java.lang.ProcessImpl.create(Native Method)\r\n\tat java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:420)\r\n\tat java.base/java.lang.ProcessImpl.start(ProcessImpl.java:151)\r\n\tat java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)\r\n\t... 30 more\r\n"},"stage":"finished","description":"Test Description: Login test with wrong username and wrong password.","start":1526566914203,"stop":1526566938603,"attachments":[{"name":"Page screenshot","source":"d6c15598-ae15-49b6-b04b-18b6f9817f2a-attachment","type":"image/png"}],"parameters":[]}